### ISSUE TITLE
Do not build example programs by default

### ISSUE THREAD

**Issue by amigalemming** [dhess/hpio#74]
I'd prefer that example programs are not built by default. If I compile my own project with a `hpio` dependency then the `cabal/bin` directory fills up with unrelated executables and it prolongs compilation time.
Thus I propose to declare:
~~~~
flag examples
  description: Build the example programs
  manual: True
  default: False
~~~~
in the Cabal file.

**Comment by dhess** [comment]
I think this is a reasonable default. I'll add it to the todo list.
